### ISSUE TITLE
Relation (no pun intended) to the profile link relation

### ISSUE THREAD

**Issue by odrotbohm** [dret/I-D#32] opened 2016-02-22 14:45 UTC
When reading the spec document, my first reaction was: isn't that sort of a variant of the profile link relation? AFAIU a profile link points to a resource which defines semantics within the currently used media type, whether it's additional link relations, field semantics in the representation format etc.

So far I've used a profile link to point to descriptions of a service (ALPS, JSON Schema) and I can see that it might make sense to distinguish between description and documentation. I just wonder if there's anything beyond that I miss. Might be worth to clarify in the RFC, too.

**Comment by dret** [comment] 2016-02-22 20:17
On 2016-02-22 15:45, Oliver Gierke wrote:
> When reading the spec document, my first reaction was: isn't that sort
> of a variant of the profile link relation? AFAIU a profile link points
> to a resource which defines semantics within the currently used media
> type, whether it's additional link relations, field semantics in the
> representation format etc.

that's not what the profile link relation type is intended to do. the 
intention of profile is to indicate a profile (and not to point to 
anything), and the profile can be a subset, or can be extensions, or both.

> So far I've used a profile link to point to descriptions of a service
> (ALPS, JSON Schema) and I can see that it might make sense to
> distinguish between description and documentation. I just wonder if
> there's anything beyond that I miss. Might be worth to clarify in the
> RFC, too.

a profile linked from a feed may be used to indicate something along 
these lines:

"this representation uses application/atom+xml, but it also conforms to 
the additional restrictions defined by the podcast flavor of feeds."

https://tools.ietf.org/html/rfc6906#section-5.3

a service-doc linked from that same feed could link to documentation 
about a media service that allows you to browse and purchase media 
resources; the specific feed then may be the result of some interaction 
that requested "show me the podcasts i can buy".

my personal design preference could be to only have a "home" link in 
said feed, and to the link to the service-doc from that home document.

https://github.com/mnot/I-D/issues/41

**Comment by dret** [comment] 2016-02-29 09:16
does this explanation make any sense? if not, could you please rephrase why you think that service-* links and profile are closely related?

**Comment by olivergierke** [comment] 2016-02-29 09:43
> that's not what the profile link relation type is intended to do. the intention of profile is to indicate a profile (and not to point to anything), and the profile can be a subset, or can be extensions, or both.

I see. I've seen profile URIs being resolved into machine readable definitions in quite a few occasions, even if that's just been the case due to the lack of any other official means to make clients discover machine readable service descriptions. It might be me but expecting a link of a predefined link relation *not* to be followed feels kind of weird to me. I can see that it's not the primarily intended purpose, but it shouldn't surprise anyone that people actually do that, especially in a context of REST, where following links to investigate the service is a promoted concept.

> a profile linked from a feed may be used to indicate something along these lines: "this representation uses application/atom+xml, but it also conforms to the additional restrictions defined by the podcast flavor of feeds." https://tools.ietf.org/html/rfc6906#section-5.3

To be completely honest, I don't quite get the difference to the server returning a hypermedia-capable media type, with a profile link pointing to some ALPS descriptor that basically expresses: "This is (e.g.) HAL, but by the way, the documents returned also conforms to these specs, so that a more specific client aware of those semantics can provide more sophisticated functionality on top of it? The only difference here actually is that the podcasts URI is not necessarily expected to be machine readable itself. but does the profile link relation spec rule that kind of usage out really?

In a concrete example a home document serves a profile link that in turn returns a HAL document and the client can basically match the link relations found in the root service document to the ones provided by the profile resource so that the client can obtain both an ALPS (state navigation) and JSON schema description (payload description) for all the links it will find in the actual service. So far, I didn't consider this completely off the charts.

The approach was mainly influenced by @mamund's RESTful Web APIs (Chapter 8, Profiles), that starts with profile links pointing to human readable documentation but then continues to dive into XMDP and ALPS as machine readable alternatives to that.

**Comment by dret** [comment] 2016-02-29 10:34
On 2016-02-29 10:43 , Oliver Gierke wrote:
>     that's not what the profile link relation type is intended to do.
>     the intention of profile is to indicate a profile (and not to point
>     to anything), and the profile can be a subset, or can be extensions,
>     or both.
> I see. I've seen profile URIs being resolved into machine readable
> definitions in quite a few occasions, even if that's just been the case
> due to the lack of any other official means to make clients discover
> machine readable service descriptions. It might be me but expecting a
> link of a predefined link relation /not/ to be followed feels kind of
> weird to me. I can see that it's not the primarily intended purpose, but
> it shouldn't surprise anyone that people actually do that, especially in
> a context of REST, where following links to investigate the service is a
> promoted concept.

nobody can and will keep you from making profile URIs dereferencable, 
and that's fine. but they are intended to be identifiers (i.e., indicate 
semantics by value, not by reference), so don't be surprised if clients 
do not dereference that URI and assume well-defined semantics to be 
indicated by the profile URI.

to put it differently: because profile URIs are defined as 
self-contained identifiers, putting up descriptions at where they point 
is fine, as long as you never ever change those descriptions. if you do 
(and assume that clients will find out that you changed the identifier 
semantics by dereferencing the URI), then you're doing something wrong.

>     a profile linked from a feed may be used to indicate something along
>     these lines: "this representation uses application/atom+xml, but it
>     also conforms to the additional restrictions defined by the podcast
>     flavor of feeds." https://tools.ietf.org/html/rfc6906#section-5.3
> To be completely honest, I don't quite get the difference to the server
> returning a hypermedia-capable media type, with a profile link pointing
> to some ALPS descriptor that basically expresses: "This is (e.g.) HAL,
> but by the way, the documents returned also conforms to these specs, so
> that a more specific client aware of those semantics can provide more
> sophisticated functionality on top of it? The only difference here
> actually is that the podcasts URI is not necessarily expected to be
> machine readable itself. but does the profile link relation spec rule
> that kind of usage out really?

a resource can be a podcast and be a part of some service. you may ant 
to indicate both. by using profile, you can indicate that the resource 
itself follows a profile of a given media type, it follows the 
additional constraints of the "podcast spec" indicated by the podcast 
profile URI. this alone lets any client understand that when they 
retrieve that resource, they may want to do something special, such as 
saying "hey, this feed actually is a podcast" in display a little 
podcast badge in their UI.

that this podcast may be part of a bigger set of linked services is an 
orthogonal issue. that's what you may want to indicate via service-* 
links, saying that this resource, which per its profile is a podcast 
feed, also is a podcast feed that is part of some interlinked set of 
resources that may provide all kinds of podcast-related (and other) 
services.

to be honest, i am not quite understanding how these things overlap at 
all. but then again, when defining and talking about "profiles" it 
became clear that this is a very loaded term, and that the concept of a 
profile means sometimes very different things to different people.

> In a concrete example a home document serves a profile link that in turn
> returns a HAL document and the client can basically match the link
> relations found in the root service document to the ones provided by the
> profile resource so that the client can obtain both an ALPS (state
> navigation) and JSON schema description (payload description) for all
> the links it will find in the actual service. So far, I didn't consider
> this completely off the charts.

to me, that's not what "profile" was intended to do. you clearly make 
the profile depend on runtime behavior (the profile makes no sense 
without dereferencing the URI), whereas it is not defined like that. how 
you're using "profile" here is exactly what service-* is intended to do, 
so now i understand why you're seeing an overlap.

to contrast that with the intended use: if you defined a specific flavor 
of home documents, and then indicated that via a profile URI to tell the 
world "this is a home document, but it also has a special flavor as 
indicated by this identifier, and if you know and care, feel free to 
treat it as this special kind of home document", then this would be what 
"profile" is intended to do. you would still use service-* to link to 
the documentation/description of what the service rooted at that home 
document is all about.

**Comment by dret** [comment] 2018-01-22 09:38
was this discussion sufficient? if not, what else needs to be discussed/changed? if yes, i assume it's ok to close this issue?

**Comment by dret** [comment] 2018-12-06 17:53
closing issue due to inactivity.

**Closed by dret** 2018-12-06 17:53 UTC
Labels: service-link-rel
